In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format',lambda x:'%.2f' %x)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split,cross_val_score

In [4]:
df=pd.read_csv('/content/advertising.csv')
df.head()

TV  radio  newspaper  sales
0 230.10  37.80      69.20  22.10
1  44.50  39.30      45.10  10.40
2  17.20  45.90      69.30   9.30
3 151.50  41.30      58.50  18.50
4 180.80  10.80      58.40  12.90

In [7]:
# multiple linear regression

X=df.drop('sales',axis=1)   # bağımsız değişkenler
y=df[['sales']]             # bağımlı değişkenler

In [8]:
# model

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.20, random_state=1)

In [9]:
X_train.shape

(160, 3)

In [10]:
X_test.shape

(40, 3)

In [11]:
y_train.shape

(160, 1)

In [13]:
reg_model=LinearRegression().fit(X_train,y_train)

In [16]:
#sabit(b-bias)
reg_model.intercept_

array([2.90794702])

In [17]:
# coefficients (w-weights)
reg_model.coef_

array([[0.0468431 , 0.17854434, 0.00258619]])

In [23]:
# tahmin

# gözlem değerlerine göre satışın beklenen değeri nedir?
# TV: 30
# radio:10
# newspaper: 40

# Sales= 2.90 + TV * 0.04 + radio * 0.17 + newspaper * 0.002
2.90 + 30*0.04+10*0.17+40*0.002

5.88

In [31]:
yeni_veri=[[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T

reg_model.predict(yeni_veri)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.202131]])

In [32]:
# tahmin başarısını değerlendirme

# Train RMSE
y_pred=reg_model.predict( X_train)
np.sqrt(mean_squared_error(y_train, y_pred))

np.float64(1.736902590147092)

In [33]:
# Train RKARE
reg_model.score(X_train, y_train)

0.8959372632325174

In [34]:
# Test RMSE
y_pred=reg_model.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))

np.float64(1.4113417558581587)

In [35]:
# Test RKARE - bağımsız değişkenlerin bağımlı değişkenleri açıklama yüzdesi
reg_model.score(X_test, y_test)

0.8927605914615384

In [36]:
# 10 katlı CV RMSE - veri seti boyutu az olduğ için daha güvenilir
np.mean(np.sqrt(-cross_val_score(reg_model,X, y, cv=10, scoring='neg_mean_squared_error')))

np.float64(1.6913531708051797)